//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPUSet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Architecture { get; set; }
        public string Cores { get; set; }
        public string Chastota { get; set; }
        public string KESHL1 { get; set; }
        public string KESHL2 { get; set; }
        public string KESHL3 { get; set; }
        public string GPU { get; set; }
        public string RAM { get; set; }
        public string TDP { get; set; }
    }
}
