//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphicsCardSet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string GraphicsCore { get; set; }
        public string Cores { get; set; }
        public string Herts { get; set; }
        public string VRAM { get; set; }
        public string Voltage { get; set; }
        public byte[] Photo { get; set; }
        public byte[] PDF { get; set; }
    }
}
