//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetMarket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternetMarketDateEntities : DbContext
    {
        public InternetMarketDateEntities()
            : base("name=InternetMarketDateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComputersSet> ComputersSet { get; set; }
        public virtual DbSet<PhonesSet> PhonesSet { get; set; }
        public virtual DbSet<TivisetSet> TivisetSet { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
        public virtual DbSet<Director> DirectorSet { get; set; }
        public virtual DbSet<Country> CountrySet { get; set; }
        public virtual DbSet<OblastDataSet> OblastDataSetSet { get; set; }
        public virtual DbSet<RegionData> RegionDataSet { get; set; }
        public virtual DbSet<CityData> CityDataSet { get; set; }
        public virtual DbSet<OrganizationSet> OrganizationSetSet { get; set; }
        public virtual DbSet<OrganizationPositionSet> OrganizationPositionSetSet { get; set; }
        public virtual DbSet<CkladSet> CkladSetSet { get; set; }
        public virtual DbSet<StreetSet> StreetSetSet { get; set; }
        public virtual DbSet<KassaSet> KassaSetSet { get; set; }
        public virtual DbSet<BankSet> BankSetSet { get; set; }
        public virtual DbSet<TabletSet> TabletSetSet { get; set; }
        public virtual DbSet<DocForPain> DocForPainSet { get; set; }
        public virtual DbSet<GraphicsCard> GraphicsCardSet { get; set; }
        public virtual DbSet<Laptops> LaptopsSet { get; set; }
        public virtual DbSet<Dogovor> DogovorSet { get; set; }
        public virtual DbSet<ZakazPokupatelya> ZakazPokupatelyaSet { get; set; }
        public virtual DbSet<Printers> PrintersSet { get; set; }
        public virtual DbSet<Boilers> BoilersSet { get; set; }
        public virtual DbSet<CPUSet> CPUSet { get; set; }
        public virtual DbSet<Mail> MailSet { get; set; }
        public virtual DbSet<Entity1> Entity1Set { get; set; }
        public virtual DbSet<SmtpServers> SmtpServersSet { get; set; }
    }
}
