//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabletSetSet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Processor { get; set; }
        public string RAM { get; set; }
        public string GPU { get; set; }
        public string Resolution { get; set; }
        public string Battery { get; set; }
    }
}
