//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TivisetSet
    {
        public int Id { get; set; }
        public string Firm { get; set; }
        public string Model { get; set; }
        public string Quantity { get; set; }
        public string Cost { get; set; }
        public byte[] Photo { get; set; }
        public byte[] PDF { get; set; }
    }
}
