//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazPokupatelya
    {
        public int Id { get; set; }
        public string Organization { get; set; }
        public string Contragent { get; set; }
        public string Sklad { get; set; }
        public string Ysluga { get; set; }
        public string Data { get; set; }
    }
}
